version: "3.6"

services:
  postgres:
    env_file:
      - ".env"
    image: "postgres:10.4-alpine"
    volumes:
      - "postgres:/var/lib/postgresql/data"

  webpack:
    build:
      context: "$PWD"
      dockerfile: "Dockerfile.webpack"
    command: yarn run watch
    ports:
      - "8001:8001"
    volumes:
      - "$PWD:/app"
      - "static:/app/priv/static"

  web:
    build: "$PWD"
    depends_on:
      - "postgres"
      - "webpack"
    env_file:
      - ".env"
    ports:
      - "8000:8000"
    stdin_open: True
    tty: True
    volumes:
      - "$PWD:/app"
      - "static:/app/priv/static"

volumes:
  postgres: {}
  static:
    driver_opts:
      device: "tmpfs"
      type: "tmpfs"
