version: "3.6"

services:
  web:
    build:
      context: "."
      args:
        - NODE_ENV=development
    command: yarn run development
    ports:
      - "8000:8000"
    env_file:
      - ".env"
      - ".env.production"
    volumes:
      - "$PWD:/app"
