version: "3.6"

services:
  postgres:
    env_file:
      - ".env"
      - ".env.production"
    image: "postgres:10.4-alpine"
    volumes:
      - "postgres:/var/lib/postgresql/data"

  web:
    build:
      context: "$PWD"
      args:
        - RAILS_ENV=development
    env_file:
      - ".env"
      - ".env.production"
    depends_on:
      - "postgres"
    ports:
      - "8000:8000"
    volumes:
      - "$PWD:/app"

volumes:
  postgres: {}
